---
- name: Include vars
  ansible.builtin.include_vars: ../../../../data/ansible/ansible_vars.yml

- name: Create group
  ansible.builtin.group:
    name: radarr
    gid: "{{ media_group }}"
    state: present

- name: Create user
  ansible.builtin.user:
    name: radarr
    group: radarr
    uid: "{{ default_user }}"
    shell: /sbin/nologin
    state: present
    create_home: false

- name: Install packages
  apt:
    pkg:
      - curl
      - mediainfo
      - sqlite3
    state: latest

- name: Install Radarr
  unarchive:
    src: https://github.com/Radarr/Radarr/releases/download/v4.2.4.6635/Radarr.master.4.2.4.6635.linux-core-x64.tar.gz
    dest: /opt/
    remote_src: true
    owner: radarr
    group: radarr
    creates: /opt/Radarr
  notify:
    - restart radarr

- name: Copy systemd service file to server
  copy:
    src: radarr.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: 0644
  notify:
    - start radarr