---
- name: Include vars
  ansible.builtin.include_vars: ../../../../data/ansible/ansible_vars.yml

- name: Install packages
  apt:
    pkg:
      - curl
      - sqlite3
    state: latest

- name: Create Prowlarr group
  group:
    name: prowlarr
    gid: "{{ default_group }}"
    state: present

- name: Create Prowlarr user
  user:
    name: prowlarr
    groups: prowlarr
    shell: /sbin/nologin
    append: yes
    state: present
    uid: "{{ default_user }}"
    create_home: no

- name: Install Prowlarr
  unarchive:
    src: https://github.com/Prowlarr/Prowlarr/releases/download/v0.4.7.2016/Prowlarr.develop.0.4.7.2016.linux-core-x64.tar.gz
    dest: /opt/
    remote_src: yes
    creates: /opt/Prowlarr
    owner: prowlarr
    group: prowlarr
  notify:
    - restart prowlarr

- name: Copy systemd service file to server
  copy:
    src: prowlarr.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: 0644
  notify:
    - start prowlarr