---
- name: start deluged
  systemd:
    name: deluged
    state: started
    enabled: true
    daemon_reload: true

- name: restart deluged
  systemd:
    name: deluged
    state: restarted
    daemon_reload: true

- name: start deluge-web
  systemd:
    name: 'deluge-web'
    state: started
    enabled: true
    daemon_reload: true

- name: restart deluge-web
  systemd:
    name: 'deluge-web'
    state: restarted
    daemon_reload: true