---
- name: Include vars
  ansible.builtin.include_vars: ../../../../data/ansible/ansible_vars.yml

- name: Install packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true

- name: Create Overseerr group
  group:
    name: overseerr
    gid: "{{ default_group }}"
    state: present

- name: Create Overseerr user
  user:
    name: overseerr
    groups: overseerr
    shell: /sbin/nologin
    append: yes
    state: present
    uid: "{{ default_user }}"
    create_home: no

- name: Add the Docker repository Apt signing key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
    keyring: /etc/apt/trusted.gpg.d/docker.gpg

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/debian bullseye stable
    state: present
  changed_when: false

- name: Install packages
  apt:
    pkg:
      - docker-ce 
    state: latest

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Create Overseerr container
  community.docker.docker_container:
    name: overseerr
    image: sctx/overseerr
    restart: true
    volumes:
      - /mnt/appdata/overseerr:/app/config
    published_ports:
      - "5055:5055"
    env:
      TZ: America/Los_Angeles
    user: 1001