---
- name: Include vars
  ansible.builtin.include_vars: ../../../../data/ansible/ansible_vars.yml

- name: Create group
  ansible.builtin.group:
    name: nzbget
    gid: "{{ media_group }}"
    state: present

- name: Create user
  ansible.builtin.user:
    name: nzbget
    group: nzbget
    uid: "{{ default_user }}"
    shell: /sbin/nologin
    state: present
    create_home: false

- name: Download NZBGet
  get_url:
    url: https://github.com/nzbget/nzbget/releases/download/v21.2-r2333/nzbget-21.2-testing-r2333-bin-linux.run
    dest: /nzbget-21.2-r2333-bin-linux.run
    mode: 0744
  register: new_nzb_dowloaded

- name: Install NZBGet if not already installed
  when: new_nzb_dowloaded.changed
  ansible.builtin.command:
    argv:
      - /nzbget-21.2-r2333-bin-linux.run
      - --destdir
      - /opt/nzbget
  notify:
    restart nzbget

- name: Recursively change ownership of NZBGet directory
  ansible.builtin.file:
    path: /opt/nzbget/
    state: directory
    recurse: yes
    owner: nzbget
    group: nzbget

- name: Copy config on first load
  ansible.builtin.copy:
    force: no
    owner: nzbget
    group: nzbget
    # remote_src: yes
    # src: /opt/nzbget/nzbget.conf
    src: nzbget.init.conf
    dest: /mnt/appdata/nzbget/nzbget.conf

- name: Copy systemd service file to server
  copy:
    src: nzbget.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: 0644
  notify:
    - start nzbget