---
http:
  routers:
    to-overseerr-secure:
      rule: Host(`tv.{{ env "DOMAIN_1" }}`)
      service: overseerr
      tls:
        certResolver: letsencrypt

  services:
    overseerr:
      loadBalancer:
        servers:
          - url: http://overseerr.dmz.local:5055