---
- name: Include vars
  ansible.builtin.include_vars: ../../../../data/ansible/ansible_vars.yml

- name: Create Traefik group
  ansible.builtin.group:
    name: traefik
    gid: "{{ default_group }}"
    state: present

- name: Create Traefik user
  ansible.builtin.user:
    name: traefik
    group: traefik
    uid: 1002
    shell: /sbin/nologin
    state: present
    create_home: false

- name: get cifs package
  ansible.builtin.package:
    name: cifs-utils
    state: present

- name: make mountpoint if needed
  ansible.builtin.file:
    path: "/mnt/appdata/traefik_dmz"
    state: directory
    mode: "0755"
    owner: traefik
    group: traefik

# /etc/fstab
# //{smb_ip}/appdata_big/traefik_dmz cifs username=traefik,password={password} 0 0
# - name: Mount network share
#   ansible.posix.mount:
#     src: "//{{ smb_ip }}/appdata_big/traefik_dmz"
#     path: "/mnt/appdata/traefik_dmz"
#     fstype: cifs
#     opts: 'username=traefik,password={{ traefik_smb_password }}'
#     state: mounted

- name: Install Traefik
  ansible.builtin.unarchive:
    src: https://github.com/traefik/traefik/releases/download/v2.10.4/traefik_v2.10.4_linux_amd64.tar.gz
    dest: /usr/local/bin
    remote_src: true
  notify:
    - restart traefik

- name: Set port binding capability on Traefik
  community.general.capabilities:
    path: /usr/local/bin/traefik
    capability: cap_net_bind_service+ep
    state: present

- name: Copy Traefik config
  ansible.builtin.copy:
    src: traefik
    dest: /etc
    mode: 0755
  notify:
    - restart traefik

- name: Create Traefik config file
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: /etc/traefik/traefik.yml
    mode: 0644
  notify:
    - restart traefik

- name: Create Traefik service
  ansible.builtin.template:
    src: traefik.service.j2
    dest: /etc/systemd/system/traefik.service
    mode: 0644
    owner: root
    group: root
  notify:
    - start traefik