---
http:
  routers:
    to-bazarr:
      rule: "Host(`bazarr.test`, `subtitles.test`)"
      service: bazarr

  services:
    bazarr:
      loadBalancer:
        servers:
          - url: http://bazarr.max.local:6767