---
http:
  routers:
    to-deluge:
      rule: "Host(`torrents.test`, `deluge.test`)"
      service: deluge

  services:
    deluge:
      loadBalancer:
        servers:
          - url: http://deluge.max.local:8112