---
http:
  routers:
    to-lidarr:
      rule: "Host(`music.test`, `lidarr.test`)"
      service: lidarr

  services:
    lidarr:
      loadBalancer:
        servers:
          - url: http://lidarr.max.local:8686