---
http:
  routers:
    to-nzbget:
      rule: "Host(`nzb.test`, `usenet.test`, `nzbget.test`)"
      service: nzbget

  services:
    nzbget:
      loadBalancer:
        servers:
          - url: http://nzbget.max.local:6789