---
http:
  routers:
    to-omada:
      rule: "Host(`omada.test`, `wifi.test`)"
      service: omada

  services:
    omada:
      loadBalancer:
        servers:
          - url: http://omada.max.local:8088