---
http:
  routers:
    to-overseerr:
      rule: "Host(`overseerr.test`)"
      service: overseerr

  services:
    overseerr:
      loadBalancer:
        servers:
          - url: http://overseerr.max.local:5055