---
http:
  routers:
    to-plex:
      rule: "Host(`plex.test`)"
      service: plex
    to-plex-secure:
      rule: Host(`plex.{{ env "DOMAIN_1" }}`)
      service: plex
      tls:
        certResolver: letsencrypt

  services:
    plex:
      loadBalancer:
        servers:
          - url: http://plex.max.local:32400