---
http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

  routers:
    to-pve:
      rule: "Host(`pve.test`, `proxmox.test`, `server.test`)"
      middlewares:
      - redirect-to-https
      service: pve

  services:
    pve:
      loadBalancer:
        servers:
          - url: https://pve.max.local:8006