---
http:
  routers:
    to-radarr:
      rule: "Host(`movies.test`, `radarr.test`)"
      service: radarr

  services:
    radarr:
      loadBalancer:
        servers:
          - url: http://radarr.max.local:7878