---
http:
  routers:
    to-sonarr:
      rule: "Host(`tv.test`, `sonarr.test`)"
      service: sonarr

  services:
    sonarr:
      loadBalancer:
        servers:
          - url: http://sonarr.max.local:8989