# yaml-language-server: $schema=https://json.schemastore.org/traefik-v2-file-provider.json
---
http:
  routers:
    api:
      rule: "Host(`traefik.max.local`) || Host(`traefik.test`)"
      service: api@internal