---
- name: Include vars
  ansible.builtin.include_vars: ../../../../data/ansible/ansible_vars.yml

- name: Create group
  ansible.builtin.group:
    name: bazarr
    gid: "{{ default_group }}"
    state: present

- name: Create user
  ansible.builtin.user:
    name: bazarr
    group: bazarr
    uid: "{{ default_user }}"
    shell: /sbin/nologin
    state: present
    create_home: false

- name: Install packages
  apt:
    pkg:
      - python3-pip
      - python3-distutils
      - unzip
    state: latest

- name: Create Bazarr directory if it does not exist
  ansible.builtin.file:
    path: /opt/bazarr
    state: directory
    mode: 0755

- name: Install Bazarr
  unarchive:
    src: https://github.com/morpheus65535/bazarr/releases/download/v1.1.2/bazarr.zip
    dest: /opt/bazarr
    remote_src: true
    creates: /opt/bazarr/bazarr/
    owner: bazarr
    group: bazarr

- name: Install specified python requirements
  pip:
    requirements: /opt/bazarr/requirements.txt

# - name: Recursively change ownership of Bazarr directory
#   ansible.builtin.file:
#     path: /opt/bazarr/
#     state: directory
#     recurse: true
#     owner: bazarr
#     group: bazarr

- name: Copy systemd service file to server
  copy:
    src: bazarr.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: 0644
  notify:
    - start bazarr